services:
  bindle:
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - bindle-server/.env
      - bindle-client/.env
    environment:
      - ENVIRONMENT=production
    volumes:
      - bindle_data:/root/sqlite.db
    restart: unless-stopped

volumes:
  bindle_data:
