services:
  bindle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./bindle-server/.env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
