services:
  bindle:
    build:
      dockerfile: Dockerfile
      args:
        VITE_CONTACT_EMAIL: ${VITE_CONTACT_EMAIL}
    ports:
      - "3001:3000"
    env_file:
      - bindle-server/.env
      - bindle-client/.env
    environment:
      - ENVIRONMENT=production
    volumes:
      - type: volume
        source: bindle_data
        target: /app/storage/
    restart: unless-stopped
volumes:
  bindle_data:
    name: bindle_data
